#Boucle de test si les joueurs sont présent
/testfor @a[x=-853,y=130,z=-1103,dx=-28,dy=2,dz=-18]
#Lance le monologue D'Etotsira
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Tu es en sécurité à présent. Navré, je n'ai pas pu sauver ton équipement.",color:blue,bold:false,extra:[{text:"                      [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1045 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Laisse moi t'expliquer pourquoi tu es là : Notre univers est composé de 7 dimensions appelées les 7 royaumes, chaque dimension est liée aux autres par des portails qui assurent les flux de matière, d'énergie et de magie entre ces mondes.",color:blue,bold:false,extra:[{text:"                          [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1048 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Notre histoire commence sur Tellurön appelé Terre à ton époque.",color:blue,bold:false,extra:[{text:"                            [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1051 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Il y a longtemps, Ranégot, un immortel, jadis grand conquérant et détenteur du trône de Tellurön, s'est emparé de la source de pouvoir des 7 royaumes en Angband (Nether).",color:blue,bold:false,extra:[{text:"                                       [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1054 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Cependant les forces liées à cette source sont maléfiques, et il ne tarda pas à être corrompu par celle-ci.",color:blue,bold:false,extra:[{text:"                                            [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1057 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Tentant d'étendre l'étreinte du mal sur les autres dimensions, les différents souverains de Tellurön ainsi que les autres rois des 7 royaumes unirent leur force et leur savoir pour l'arrêter.",color:blue,bold:false,extra:[{text:"                       [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1060 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"9 gemmes recélant tous les types de magie furent crées, et de ce fait Ranégot fut stoppé. Nous l'enfermâmes durant de longs siècles mais il parvînt à s'échapper.",color:blue,bold:false,extra:[{text:"                                            [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1063 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Cependant il ne put rejoindre la source de pouvoir, dite source de corruption, car nous avions condamné le royaumes de Angband. Il ne put restituer l'ensemble de ses pouvoirs.",color:blue,bold:false,extra:[{text:"                                      [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1066 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Un jour, un prophète a annoncé la venue d'une nouvelle source de pouvoir, sur Tellurön. Ranégot a donc voyagé dans le temps pour s'en emparer.",color:blue,bold:false,extra:[{text:"      [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1069 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"La seule force magique nécessaire pour arrêter Ranégot se trouve enfouie au sein des 9 gemmes que nous avons nous même cachés 1 millénaire auparavant.",color:blue,bold:false,extra:[{text:"                                                             [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1072 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Tous les sanctuaires qui les renferment sont maintenant occupé par les forces du mal, elles même attiré par la magie émanant des gemmes. Nous avons déjà envoyé des légions entières à leur recherche mais sans succès.",color:blue,bold:false,extra:[{text:"                                                   [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1075 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Concernant ton époque, le prophète a malheureusement annoncé que la venue de cette nouvelle source provoquerait un véritable génocide sur l'humanité. Mais il a aussi prédit que dans ce chaos, une lumière brillerait, et qu'elle sera la clef du destin de tous les mondes.",color:blue,bold:false,extra:[{text:"                                                               [--->]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1078 redstone_block"},hoverEvent:{action:show_text,value:"Lire la suite..."}}]}]}
/tellraw @a {text:" -°- Voix désincarnée : ",color:gray,bold:true,extra:[{text:"Tu es l'élu... Tu es le seul à pouvoir trouver les gemmes, tu ne t'en rends pas encore compte mais tu es notre meilleur et dernier atout, nous ferons notre maximum pour t'aider. Bonne chance...",color:blue,bold:false,extra:[{text:"                                                                                   [Continuer]",color:dark_green,clickEvent:{action:run_command,value:"/setblock -941 126 -1081 redstone_block"},hoverEvent:{action:show_text,value:"Avance vers la lumière..."}}]}]}

/tellraw @a {text:"Il me semble que je dois écouter entièrement le sage avant d'aller ici...",color:aqua}