#Entrance
execute if entity @a[x=-121,y=90,z=-1625,distance=..15,gamemode=adventure]
tellraw @a {"text":"Bon si je me souviens bien pour entrer dans le donjon il faut que j'active les interrupteurs des 2 guardiens en tirant dans leur bouche crachant du feu! Puis, je dois activer 3 autres interrupteurs accrochés sur la falaise, uniquement la : roue de Diamant, de Lapis et d'Emeraude!","color":"aqua"}
playsound music_disc.chirp music @a -128 79 -1606 10.0 1.0 1.0

#Left Fire Shot
setblock -133 80 -1601 air
summon horse -126 87 -1611 {PersistenceRequired:1b,Type:4,Variant:0,Tame:1b,Saddle:0,drop_chances:{mainhand:0.0f,feet:0.0f,legs:0.0f,chest:0.0f,head:0.0f},attributes:[{id:max_health,base:100},{id:movement_speed,base:0.2},{id:jump_strength,base:0.2}],Passengers:[{id:skeleton,PersistenceRequired:1b,attributes:[{id:max_health,base:80},{id:attack_damage,base:5.0},{id:follow_range,base:30.0}],drop_chances:{mainhand:0.09f,feet:0.08f,legs:0.09f,chest:0.08f,head:0.09f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{power:3,punch:1}}},feet:{id:diamond_boots,count:1,components:{enchantments:{projectile_protection:2,thorns:1}}},legs:{id:iron_leggings,count:1,components:{enchantments:{protection:1,thorns:1}}},chest:{id:iron_chestplate,count:1,components:{enchantments:{protection:2,thorns:1}}},head:{id:chainmail_helmet,count:1,components:{enchantments:{protection:2,projectile_protection:3}}}}}]}

#Right Fire Shot
setblock -110 80 -1601 air
summon skeleton -118 87 -1611 {PersistenceRequired:1b,Type:4,Variant:0,Tame:1b,Saddle:0,drop_chances:{mainhand:0.0f,feet:0.0f,legs:0.0f,chest:0.0f,head:0.0f},attributes:[{id:max_health,base:100},{id:movement_speed,base:0.2},{id:jump_strength,base:0.2}],Passengers:[{id:skeleton,PersistenceRequired:1b,attributes:[{id:max_health,base:80},{id:attack_damage,base:5.0},{id:follow_range,base:30.0}],drop_chances:{mainhand:0.09f,feet:0.08f,legs:0.09f,chest:0.08f,head:0.09f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{power:3,punch:1}}},feet:{id:diamond_boots,count:1,components:{enchantments:{projectile_protection:2,thorns:1}}},legs:{id:iron_leggings,count:1,components:{enchantments:{protection:1,thorns:1}}},chest:{id:iron_chestplate,count:1,components:{enchantments:{protection:2,thorns:1}}},head:{id:chainmail_helmet,count:1,components:{enchantments:{protection:2,projectile_protection:3}}}}}]}


#When both Fire are Shot
summon zombie ~ ~8 ~ {PersistenceRequired:1b,AbsorptionAmount:10,IsBaby:1b,drop_chances:{mainhand:0.0f,feet:0.0f,legs:0.0f,chest:0.0f,head:0.0f},equipment:{mainhand:{id:wooden_hoe,count:1},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
#cette commande x12


# When Emerald, Diamond and Lapis lever are pulled
tellraw @a {"text":"Une ouverture s'est créée dans la roue du Lapis Lazuli!","italic":true,"color":"gray"}
summon zombified_piglin -122 101 -1655 {PersistenceRequired:1b,attributes:[{id:max_health,base:100},{id:attack_damage,base:3.0}],drop_chances:{mainhand:0.001f,feet:0.0f,legs:0.0f,chest:0.002f,head:0.0f},equipment:{mainhand:{id:diamond_axe,count:1,components:{enchantments:{sharpness:10,unbreaking:5},custom_name:{text:"IMMORTAL KING'S DIAMOND CRUSHER"},lore:["Legendary Axe!","Immortal King's Set!"]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:diamond_chestplate,count:1,components:{enchantments:{protection:6,thorns:4,unbreaking:10},custom_name:{text:"IMMORTAL KING'S SOUL CAGE"},lore:["Legendary Chestplate!","Immortal King's Set!"]}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
playsound entity.experience_orb.pickup master @a
playsound entity.player.levelup master @a
summon zombie -67 91 -1663 {PersistenceRequired:1b,attributes:[{id:max_health,base:40},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{unbreaking:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:[170170170]}},head:{id:iron_helmet,count:1,components:{enchantments:{protection:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
summon zombie -67 91 -1663 {PersistenceRequired:1b,attributes:[{id:max_health,base:40},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{unbreaking:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:[170170170]}},head:{id:iron_helmet,count:1,components:{enchantments:{protection:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
summon zombie -106 91 -1676 {PersistenceRequired:1b,attributes:[{id:max_health,base:40},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:iron_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{unbreaking:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:[170170170]}},head:{id:iron_helmet,count:1,components:{enchantments:{protection:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
summon zombie -95 91 -1665 {PersistenceRequired:1b,attributes:[{id:max_health,base:40},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{unbreaking:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:[170170170]}},head:{id:iron_helmet,count:1,components:{enchantments:{protection:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
#This command has an error ? Need to check
summon zombie -73 87 -1667 {PersistenceRequired:1b,attributes:[{id:max_health,base:40},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{unbreaking:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:[170170170]}},head:{id:iron_helmet,count:1,components:{enchantments:{protection:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
summon zombie -84 91 -1663 {PersistenceRequired:1b,attributes:[{id:max_health,base:40},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{unbreaking:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:[170170170]}},head:{id:iron_helmet,count:1,components:{enchantments:{protection:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
summon zombie -67 91 -1663 {PersistenceRequired:1b,attributes:[{id:max_health,base:40},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{unbreaking:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:[170170170]}},head:{id:iron_helmet,count:1,components:{enchantments:{protection:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
summon zombie -67 91 -1663 {PersistenceRequired:1b,attributes:[{id:max_health,base:40},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{unbreaking:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:[170170170]}},head:{id:iron_helmet,count:1,components:{enchantments:{protection:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
summon zombie -73 87 -1667 {PersistenceRequired:1b,attributes:[{id:max_health,base:40},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{unbreaking:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:[170170170]}},head:{id:iron_helmet,count:1,components:{enchantments:{protection:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}

#Iron Mechanism 1
# Play sound noteblock
summon zombie -95 91 -1664 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{protection:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:iron_helmet,count:1,components:{enchantments:{unbreaking:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
summon zombie -95 91 -1664 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{protection:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:iron_helmet,count:1,components:{enchantments:{unbreaking:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
summon zombie -95 91 -1664 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{protection:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:iron_helmet,count:1,components:{enchantments:{unbreaking:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
summon zombie -95 91 -1664 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{protection:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:iron_helmet,count:1,components:{enchantments:{unbreaking:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}
tellraw @a {"text":"Porte déverouillée!","italic":true,"color":"gray"}
summon zombie -95 91 -1664 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:2.0}],IsBaby:1b,drop_chances:{mainhand:0.09f,feet:0.07f,legs:0.08f,chest:0.0f,head:0.09f},equipment:{mainhand:{id:diamond_sword,count:1},feet:{id:iron_boots,count:1,components:{enchantments:{protection:2,feather_falling:2,unbreaking:4},custom_name:{text:"WATERWALK"},lore:["Legendary Boots!"]}},legs:{id:chainmail_chestplate,count:1,components:{enchantments:{protection:2,fire_protection:4,unbreaking:5},custom_name:{text:"MAVINA'S EMBRACE"},lore:["Legendary Chestplate!","Mavina's Set!"]}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:iron_helmet,count:1,components:{enchantments:{unbreaking:4,unbreaking:4},custom_name:{text:"GAZE"},lore:["Legendary Helm!"]}}}}

#Iron Mechanism 2
# Play sound noteblock
summon skeleton -123 94 -1671 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -122 94 -1676 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon slime -122 88 -1672 {PersistenceRequired:1b,Size:2,attributes:[{id:max_health,base:60},{id:attack_damage,base:4.0}],AbsorptionAmount:40}
summon slime -122 88 -1672 {PersistenceRequired:1b,Size:2,attributes:[{id:max_health,base:60},{id:attack_damage,base:4.0}],AbsorptionAmount:40}
summon slime -122 88 -1672 {PersistenceRequired:1b,Size:2,attributes:[{id:max_health,base:60},{id:attack_damage,base:4.0}],AbsorptionAmount:40}
summon slime -122 88 -1672 {PersistenceRequired:1b,Size:2,attributes:[{id:max_health,base:60},{id:attack_damage,base:4.0}],AbsorptionAmount:40}

#Bow Mechanism 1
summon skeleton -123 94 -1671 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -123 94 -1671 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -122 94 -1676 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -122 94 -1676 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon slime -123 89 -1673 {PersistenceRequired:1b,Size:5,CustomName:'"Blobby"',CustomNameVisible:1b,drop_chances:{mainhand:0f,head:0f,chest:0f,legs:0.5f,feet:0.5f},equipment:{mainhand:{id:diamond_sword,count:1,tag:{ench:[{id:16,lvl:5}],display:{Name:"THE GRANDFATHER",Lore:["Legendary Sword Unbreakable!"]}}},head:{id:iron_helmet,count:1,tag:{ench:[{id:0,lvl:2},{id:34,lvl:4}],Unbreakable:1,display:{Name:"GAZE",Lore:["Legendary Helm!"]}}},chest:{id:chainmail_chestplate,count:1,tag:{ench:[{id:34,lvl:3},{id:0,lvl:8}],display:{Name:"SHAM",Lore:["Legendary Chestplate!"]}}},legs:{id:magma_cream,count:1,tag:{display:{Name:"ECAILLE SOUVERAINE DU CHAOS",Lore:["Précieux!!","Très, TRES précieux........"]}}},feet:{id:magma_cream,count:1,tag:{display:{Name:"ECAILLE SOUVERAINE DU CHAOS",Lore:["Précieux!!","Très, TRES précieux........"]}}}}}
playsound entity.experience_orb.pickup master @a

#Iron Mechanism 3
tp @p -126 88 -1659
tellraw @a {"text":"Ouverture porte Ouest!","italic":true,"color":"gray"}

#Gold Mechanism 1
playsound entity.enderman.stare master @a

#Raccourcit
tp @p -79 50 -1746
scoreboard players remove @p Chronoton 30
say Vous avez prit un raccourci, mais vous perdez 30 Chronotons!

#Piege 1
summon creeper -100 55 -1693 {PersistenceRequired:1b}
#^ x17


#All key placed
playsound block.portal.travel master @a
tellraw @a {"text":"VOUS NE M'EMPECHEREZ JAMAIS DE GRANDIR!!!! L'ELEVATION VERS LES CIEUX EST MON DESTIN!!!","bold":true,"color":"red"}
tellraw @a {"text":"La porte de la grande Pyramide s'est ouverte au sommet!","italic":true,"color":"gray"}
summon skeleton -107 64 -1830 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -110 64 -1823 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -114 64 -1821 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -121 64 -1821 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -121 64 -1821 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -114 64 -1831 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -121 64 -1834 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -129 64 -1827 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -133 64 -1830 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}
summon skeleton -133 64 -1820 {PersistenceRequired:1b,attributes:[{id:max_health,base:50},{id:attack_damage,base:5.0}],drop_chances:{mainhand:0.03f,head:0f,chest:0f,legs:0f,feet:0f},equipment:{mainhand:{id:bow,count:1,components:{enchantments:{unbreaking:2,power:4},custom_name:{text:"CONFERENCE CALL"},lore:[{text:"Legendary Bow!"}]}},feet:{id:leather_boots,count:1,components:{dyed_color:170170170}},legs:{id:leather_leggings,count:1,components:{dyed_color:170170170}},chest:{id:leather_chestplate,count:1,components:{dyed_color:170170170}},head:{id:leather_helmet,count:1,components:{dyed_color:170170170}}}}

#Activation du boss
setblock -112 93 -1843 redstone_block