#FireBall
/give @a minecraft:written_book 1 0 {title:"BOULE DE FEU",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._     BOULE DE FEU     _.-*^*-._.-*^*-._\n',color:red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 1'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 30 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nInvoque une boule de feu en lévitation sur votre position.',color:blue,bold:false}]"]}

#Corruption 
/give @a minecraft:written_book 1 0 {title:"CORRUPTION",author:"Namrin",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n  _,.',color:dark_red,bold:true,underlined:false,extra:[{text:'¤;|/',color:dark_purple,underlined:false},{text:'~¨^¨~',color:black},{text:'\\\|:¤',color:dark_purple},{text:'.,_       ',color:dark_red,underlined:false,bold:true},{text:'CORRUPTION',strikethrough:true,color:black,bold:true},{text:'      ~``',color:dark_red,bold:true,underlined:false},{text:'*|;\\\',color:dark_purple},{text:',_._,',color:black},{text:'/;|*',color:dark_purple},{text:'``~\n',color:dark_red,underlined:false,bold:true}],clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 2'},hoverEvent:{action:show_text,value:'Cliquez ici pour vous déchaîner! Coût : 100 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nLégendaire magie à l’origine du mal et du chaos imprégnant chaque royaumes... Vous vous mettez dans un état de transe, vous regagnez vos point de vie. Votre force et vitesse se décuple pendant 30 secondes.',color:blue,bold:false}]","[{text:'Attention cette puissante magie a des effets secondaires néfastes...',color:blue,bold:false}]"]}

#Regain
/give @a minecraft:written_book 1 0 {title:"REGAIN",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._        REGAIN          _.-*^*-._.-*^*-._\n',color:red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 3'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 40 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nRégénère rapidement vos points de vie pendant un très court instant.',color:blue,bold:false}]"]}

#Inferno
/give @a minecraft:written_book 1 0 {title:"INFERNO",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._        INFERNO         _.-*^*-._.-*^*-._\n',color:red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 4'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 20 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nInvoque tout autour de vous une rafale de petites boules de feu enflammant ainsi vos ennemis.',color:blue,bold:false}]"]}

#Repulsion Malefique
/give @a minecraft:written_book 1 0 {title:"REPULSION MALEFIQUE",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._       REPULSION           MALEFIQUE       _.-*^*-._.-*^*-._\n',color:red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 5'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 45 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nInvoque tout autour de vous une puissante vague d’explosions maléfiques blessant ainsi les ennemis en leur provoquant des liaisons internes.',color:blue,bold:false}]"]}

#Pluie de fleches
/give @a minecraft:written_book 1 0 {title:"PLUIE DE FLECHES",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._        PLUIE DE            FLECHES        _.-*^*-._.-*^*-._\n',color:red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 6'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 40 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nInvoque une grande quantité de flèches tombant tout autour de vous blessant ainsi vos ennemis profondément.',color:blue,bold:false}]"]}

#Danses des lames
/give @a minecraft:written_book 1 0 {title:"DANSES DES LAMES",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._        DANSE DES             LAMES         _.-*^*-._.-*^*-._\n',color:red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 7'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 50 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nInvoque une série de flèches enflammées par projection autour de vous pendant 5 secondes, blessant et brulant ainsi sérieusement vos ennemis.',color:blue,bold:false}]"]}

#Marque du repos
/give @a minecraft:written_book 1 0 {title:"MARQUE DU REPOS",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._      MARQUE DU              REPOS          _.-*^*-._.-*^*-._\n',color:red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 8'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 25 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nInvoque une aura protectrice ignifuge sur le joueur, lui permettant ainsi de résister aux dégats de feu et d’éteindre les flammes sur le sol.',color:blue,bold:false}]"]}

#Ultima
/give @a minecraft:written_book 1 0 {title:"ULTIMA",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._         ULTIMA         _.-*^*-._.-*^*-._\n',color:green,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 9'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 20 Dahäl par seconde!'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true},{text:'\n '},{text:'  <!!!> STOP <!!!> ',color:dark_red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 0'},hoverEvent:{action:show_text,value:'Cliquez ici pour stopper le sortilège!'}}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nUne magie divine très puissante provoquant une irradiation de l’air autour de vous, et attirant ainsi des milliers d’éclaires en série sur vos ennemis. Celle-ci consomme votre Dahäl jusqu’à épuisement si elle n’est pas interrompue.',color:blue,bold:false}]"]}

#Holy Nova
/give @a minecraft:written_book 1 0 {title:"HOLY NOVA",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._        HOLY NOVA      _.-*^*-._.-*^*-._\n',color:red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 23'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 70 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nInvoque une nova destructrice de flèches enflammées au-dessus du joueur, provoquant ainsi de très lourd dégâts à tous les ennemis se trouvant dans un rayon de 30m.',color:blue,bold:false}]"]}

#Appat
/give @a minecraft:written_book 1 0 {title:"APPAT",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._         APPAT          _.-*^*-._.-*^*-._\n',color:red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 20'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 40 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nInvoque 4 tourelles immobiles qui lancent des boules de neiges, repoussant et appâtant ainsi certains monstres.',color:blue,bold:false}]"]}

#Ration de Survie
/give @a minecraft:written_book 1 0 {title:"RATION DE SURVIE",author:"Calypso",pages:["{text:' - Livre de magie -\n',color:gray,bold:true,extra:[{text:'\n \n'},{text:' <= Incantation => ---------------- ',color:gold,bold:true},{text:'\n _.-*^*-._.-*^*-._   RATION DE SURVIE  _.-*^*-._.-*^*-._\n',color:red,bold:true,clickEvent:{action:run_command,value:'/scoreboard players set @p MAGIE 19'},hoverEvent:{action:show_text,value:'Cliquez ici pour lancer le sort! Coût : 30 Dahäl'}},{text:'\n---------------- <= Incantation => \n',color:gold,bold:true}]}","[{text:'    Description : \n',color:black,bold:true},{text:'\nInvoque une pomme, un pain et une carotte.',color:blue,bold:false}]"]}